// MongoDB Seed Data Script
// Run: docker exec mongodb mongosh -u admin -p secure_mongo_password_change_me --authenticationDatabase admin < scripts/seed-mongodb.js

print('🌱 Starting MongoDB seed data...\n');

// IMPORTANT: Both Rust and Python now use 'bot_core' database
// All data is stored in a single unified database

const now = new Date().toISOString();
// This hash is for password: 'password123' (generated by Rust bcrypt)
const passwordHash = '$2b$12$u6jOUU6M.FNboOWd5UNsLeILy53TOozY15//Pt6sHfmdZFW/0v4fG';

// ============================================================
// 1. SEED USERS in bot_core - For Authentication
// ============================================================
print('📝 Creating users in bot_core database...');
db = db.getSiblingDB('bot_core');

// Clear existing users
db.users.deleteMany({email: {$in: ['admin@botcore.com', 'trader@botcore.com', 'viewer@botcore.com']}});

const rustUsers = [
    {
        email: 'admin@botcore.com',
        password_hash: passwordHash,
        full_name: null,
        is_active: true,
        is_admin: true,
        created_at: now,
        updated_at: now,
        last_login: null,
        settings: {
            trading_enabled: false,
            risk_level: 'Medium',
            max_positions: NumberLong('5'),
            default_quantity: 0.01,
            notifications: {
                email_alerts: true,
                trade_notifications: true,
                system_alerts: true
            }
        }
    },
    {
        email: 'trader@botcore.com',
        password_hash: passwordHash,
        full_name: null,
        is_active: true,
        is_admin: false,
        created_at: now,
        updated_at: now,
        last_login: null,
        settings: {
            trading_enabled: false,
            risk_level: 'Medium',
            max_positions: NumberLong('3'),
            default_quantity: 0.01,
            notifications: {
                email_alerts: true,
                trade_notifications: true,
                system_alerts: true
            }
        }
    },
    {
        email: 'viewer@botcore.com',
        password_hash: passwordHash,
        full_name: null,
        is_active: true,
        is_admin: false,
        created_at: now,
        updated_at: now,
        last_login: null,
        settings: {
            trading_enabled: false,
            risk_level: 'Low',
            max_positions: NumberLong('1'),
            default_quantity: 0.01,
            notifications: {
                email_alerts: false,
                trade_notifications: false,
                system_alerts: true
            }
        }
    }
];

const userResult = db.users.insertMany(rustUsers);
print(`✅ Created ${Object.keys(userResult.insertedIds).length} users in bot_core\n`);

// ============================================================
// 2. SEED SAMPLE DATA in bot_core - For Trading & AI
// ============================================================
print('📝 Creating sample data in bot_core database...');
// Already in bot_core database, no need to switch

// 2. Create Paper Trading Accounts
print('💰 Creating paper trading accounts...');
const paperAccounts = [
    {
        user_email: 'trader@botcore.com',
        balance_usdt: 10000.0,
        initial_balance: 10000.0,
        total_pnl: 0.0,
        total_trades: 0,
        win_rate: 0.0,
        created_at: new Date(),
        updated_at: new Date(),
        status: 'active',
        settings: {
            max_position_size: 0.1,
            max_leverage: 3,
            default_stop_loss: 0.02,
            default_take_profit: 0.05
        }
    },
    {
        user_email: 'admin@botcore.com',
        balance_usdt: 50000.0,
        initial_balance: 50000.0,
        total_pnl: 2500.0,
        total_trades: 45,
        win_rate: 0.67,
        created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000), // 30 days ago
        updated_at: new Date(),
        status: 'active',
        settings: {
            max_position_size: 0.2,
            max_leverage: 5,
            default_stop_loss: 0.03,
            default_take_profit: 0.08
        }
    }
];

const accountResult = db.paper_trading_accounts.insertMany(paperAccounts);
print(`✅ Created ${accountResult.insertedIds.length} paper trading accounts\n`);

// 3. Create Sample Positions
print('📊 Creating sample positions...');
const positions = [
    {
        user_email: 'trader@botcore.com',
        symbol: 'BTCUSDT',
        side: 'LONG',
        entry_price: 43250.50,
        current_price: 43890.75,
        quantity: 0.1,
        leverage: 3,
        margin: 1441.68,
        unrealized_pnl: 192.08,
        unrealized_pnl_percent: 4.44,
        stop_loss: 42305.49,
        take_profit: 45412.03,
        entry_time: new Date(Date.now() - 2 * 60 * 60 * 1000), // 2 hours ago
        updated_at: new Date(),
        status: 'open',
        strategy: 'RSI Oversold + MACD Bullish',
        risk_reward_ratio: 2.5
    },
    {
        user_email: 'admin@botcore.com',
        symbol: 'ETHUSDT',
        side: 'LONG',
        entry_price: 2285.30,
        current_price: 2312.45,
        quantity: 2.5,
        leverage: 2,
        margin: 2856.63,
        unrealized_pnl: 67.88,
        unrealized_pnl_percent: 2.38,
        stop_loss: 2240.00,
        take_profit: 2400.00,
        entry_time: new Date(Date.now() - 5 * 60 * 60 * 1000), // 5 hours ago
        updated_at: new Date(),
        status: 'open',
        strategy: 'Bollinger Bands Breakout',
        risk_reward_ratio: 2.0
    }
];

const positionResult = db.positions.insertMany(positions);
print(`✅ Created ${positionResult.insertedIds.length} open positions\n`);

// 4. Create Sample Trades (Historical)
print('📈 Creating sample trade history...');
const trades = [
    {
        user_email: 'admin@botcore.com',
        symbol: 'BTCUSDT',
        side: 'LONG',
        entry_price: 41500.00,
        exit_price: 42890.00,
        quantity: 0.2,
        leverage: 3,
        realized_pnl: 834.00,
        realized_pnl_percent: 10.06,
        entry_time: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000), // 3 days ago
        exit_time: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000), // 2 days ago
        status: 'closed',
        strategy: 'MACD Golden Cross',
        win: true,
        fees: 12.51,
        notes: 'Strong bullish momentum, exited at resistance'
    },
    {
        user_email: 'admin@botcore.com',
        symbol: 'ETHUSDT',
        side: 'LONG',
        entry_price: 2350.00,
        exit_price: 2280.00,
        quantity: 1.5,
        leverage: 2,
        realized_pnl: -105.00,
        realized_pnl_percent: -2.98,
        entry_time: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000), // 7 days ago
        exit_time: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000), // 6 days ago
        status: 'closed',
        strategy: 'RSI Oversold',
        win: false,
        fees: 8.83,
        notes: 'Stop loss hit due to market downturn'
    },
    {
        user_email: 'admin@botcore.com',
        symbol: 'BNBUSDT',
        side: 'LONG',
        entry_price: 305.50,
        exit_price: 318.90,
        quantity: 10,
        leverage: 2,
        realized_pnl: 134.00,
        realized_pnl_percent: 4.39,
        entry_time: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000), // 10 days ago
        exit_time: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000), // 8 days ago
        status: 'closed',
        strategy: 'Volume Spike + Bollinger Bands',
        win: true,
        fees: 9.73,
        notes: 'Good volume confirmation, quick profit'
    }
];

const tradeResult = db.trades.insertMany(trades);
print(`✅ Created ${tradeResult.insertedIds.length} historical trades\n`);

// 5. Create Strategy Configurations
print('⚙️ Creating strategy configurations...');
const strategies = [
    {
        name: 'RSI Oversold Strategy',
        type: 'RSI',
        enabled: true,
        parameters: {
            rsi_period: 14,
            oversold_threshold: 30,
            overbought_threshold: 70,
            min_confidence: 0.6
        },
        symbols: ['BTCUSDT', 'ETHUSDT', 'BNBUSDT'],
        created_at: new Date(),
        updated_at: new Date()
    },
    {
        name: 'MACD Crossover Strategy',
        type: 'MACD',
        enabled: true,
        parameters: {
            fast_period: 12,
            slow_period: 26,
            signal_period: 9,
            min_confidence: 0.65
        },
        symbols: ['BTCUSDT', 'ETHUSDT'],
        created_at: new Date(),
        updated_at: new Date()
    },
    {
        name: 'Bollinger Bands Strategy',
        type: 'BollingerBands',
        enabled: false,
        parameters: {
            period: 20,
            std_dev: 2,
            min_confidence: 0.7
        },
        symbols: ['BTCUSDT', 'ETHUSDT', 'BNBUSDT', 'SOLUSDT'],
        created_at: new Date(),
        updated_at: new Date()
    }
];

const strategyResult = db.strategy_configs.insertMany(strategies);
print(`✅ Created ${strategyResult.insertedIds.length} strategy configurations\n`);

// 6. Create Performance Metrics
print('📊 Creating performance metrics...');
const metrics = [
    {
        user_email: 'admin@botcore.com',
        period: 'daily',
        date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
        total_trades: 3,
        winning_trades: 2,
        losing_trades: 1,
        win_rate: 0.667,
        total_pnl: 425.50,
        total_pnl_percent: 5.32,
        max_drawdown: -2.98,
        sharpe_ratio: 1.85,
        created_at: new Date()
    },
    {
        user_email: 'admin@botcore.com',
        period: 'weekly',
        date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
        total_trades: 12,
        winning_trades: 8,
        losing_trades: 4,
        win_rate: 0.667,
        total_pnl: 1834.75,
        total_pnl_percent: 15.28,
        max_drawdown: -5.12,
        sharpe_ratio: 2.15,
        created_at: new Date()
    }
];

const metricsResult = db.performance_metrics.insertMany(metrics);
print(`✅ Created ${metricsResult.insertedIds.length} performance metrics\n`);

// 7. Create Notifications
print('🔔 Creating sample notifications...');
const notifications = [
    {
        user_email: 'trader@botcore.com',
        type: 'trade_signal',
        title: 'New Trading Signal: BTCUSDT',
        message: 'RSI Strategy suggests LONG position on BTCUSDT with 75% confidence',
        severity: 'info',
        read: false,
        created_at: new Date(Date.now() - 30 * 60 * 1000), // 30 mins ago
        data: {
            symbol: 'BTCUSDT',
            signal: 'LONG',
            confidence: 0.75,
            strategy: 'RSI'
        }
    },
    {
        user_email: 'trader@botcore.com',
        type: 'position_alert',
        title: 'Position Update: BTCUSDT',
        message: 'Your BTCUSDT position is up 4.44%. Consider taking profit.',
        severity: 'success',
        read: false,
        created_at: new Date(Date.now() - 10 * 60 * 1000), // 10 mins ago
        data: {
            symbol: 'BTCUSDT',
            pnl_percent: 4.44,
            current_price: 43890.75
        }
    },
    {
        user_email: 'admin@botcore.com',
        type: 'system_alert',
        title: 'Daily Performance Report',
        message: 'Your portfolio gained 5.32% today with 3 trades (2 wins, 1 loss)',
        severity: 'info',
        read: true,
        created_at: new Date(Date.now() - 2 * 60 * 60 * 1000), // 2 hours ago
        data: {
            total_pnl_percent: 5.32,
            total_trades: 3,
            win_rate: 0.667
        }
    }
];

const notificationResult = db.notifications.insertMany(notifications);
print(`✅ Created ${notificationResult.insertedIds.length} notifications\n`);

// Summary
print('\n🎉 Seed data creation complete!\n');
print('📊 Summary:');
print(`   Users: ${rustUsers.length}`);
print(`   Paper Trading Accounts: ${paperAccounts.length}`);
print(`   Open Positions: ${positions.length}`);
print(`   Historical Trades: ${trades.length}`);
print(`   Strategy Configs: ${strategies.length}`);
print(`   Performance Metrics: ${metrics.length}`);
print(`   Notifications: ${notifications.length}`);
print(`   AI Analysis Results: 23 (already exists)\n`);

print('🔑 Login Credentials:');
print('   Email: admin@botcore.com');
print('   Password: password123');
print('   Email: trader@botcore.com');
print('   Password: password123\n');

print('✅ You can now connect MongoDB Compass and view the data!\n');
