#!/bin/bash
# Compare old and new dependency versions
# Usage: bash compare_versions.sh

echo "=========================================="
echo "Python Dependencies Version Comparison"
echo "=========================================="
echo ""

echo "📦 UPDATED PACKAGES:"
echo "--------------------"
echo "fastapi:         0.104.1 → 0.115.5  (Security & Features)"
echo "uvicorn:         0.24.0  → 0.32.1   (Performance)"
echo "pydantic:        2.5.0   → 2.10.3   (Bug Fixes)"
echo "numpy:           1.24.3  → 1.26.4   (Compatibility)"
echo "pandas:          2.0.3   → 2.2.3    (Performance)"
echo "scikit-learn:    1.3.0   → 1.6.0    (Features)"
echo "requests:        2.31.0  → 2.32.3   (🔒 CVE-2024-35195)"
echo "pyyaml:          6.0.1   → 6.0.2    (🔒 CVE-2024-35220)"
echo "python-multipart: 0.0.6  → 0.0.20   (Security)"
echo "aiofiles:        23.2.0  → 24.1.0   (Async I/O)"
echo "joblib:          1.3.2   → 1.4.2    (Performance)"
echo "python-dotenv:   1.0.0   → 1.0.1    (Bug Fixes)"
echo "pymongo:         4.9.1   → 4.10.1   (Bug Fixes)"
echo "motor:           3.6.0   → 3.7.0    (Async Driver)"
echo "openai:          1.51.0  → 1.57.5   (GPT-4 Improvements)"
echo "ta:              0.10.2  → 0.11.0   (Technical Analysis)"
echo "loguru:          0.7.2   → 0.7.3    (Logging)"
echo "httpx:           (MISSING) → 0.28.1 (Added - Used in code)"
echo ""

echo "⏸️  KEPT AT CURRENT VERSION (Requires Testing):"
echo "-----------------------------------------------"
echo "tensorflow:      2.15.0  (Latest: 2.18.0 - Keras 3.0 changes)"
echo "torch:           2.1.0   (Latest: 2.5.1  - API changes)"
echo "torchvision:     0.16.0  (Latest: 0.20.1 - Matches torch)"
echo "torchaudio:      2.1.0   (Latest: 2.5.1  - Matches torch)"
echo "slowapi:         0.1.9   (Already latest)"
echo ""

echo "🔧 CODE CHANGES NEEDED:"
echo "----------------------"
echo "File: main.py"
echo "  Line 208:  analysis_result.dict() → analysis_result.model_dump()"
echo "  Line 1863: market_analysis.dict() → market_analysis.model_dump()"
echo "  Line 1864: risk_assessment.dict() → risk_assessment.model_dump()"
echo ""

echo "📊 DEVELOPMENT TOOLS UPDATED:"
echo "-----------------------------"
echo "pytest:          7.4.3   → 8.3.4    (Test Framework)"
echo "pytest-asyncio:  0.21.1  → 0.24.0   (Async Testing)"
echo "black:           23.7.0  → 24.10.0  (Code Formatter)"
echo "mypy:            1.5.1   → 1.13.0   (Type Checker)"
echo "jupyterlab:      4.0.5   → 4.3.3    (Notebooks)"
echo "matplotlib:      3.7.2   → 3.9.3    (Plotting)"
echo "faker:           20.1.0  → 33.1.0   (Test Data)"
echo ""

echo "✅ NEXT STEPS:"
echo "--------------"
echo "1. Review DEPENDENCY_UPDATE_NOTES.md for full details"
echo "2. Backup current environment: pip freeze > requirements.backup"
echo "3. Install updates: pip install -r requirements.updated.txt"
echo "4. Update code: Replace .dict() with .model_dump() (3 locations)"
echo "5. Run tests: pytest tests/ -v"
echo "6. Check security: pip-audit"
echo "7. If tests pass: mv requirements.updated.txt requirements.txt"
echo ""

echo "🔒 CRITICAL SECURITY UPDATES:"
echo "-----------------------------"
echo "CVE-2024-35195 (requests):        Proxy authentication leakage"
echo "CVE-2024-35220 (pyyaml):          Arbitrary code execution risk"
echo "Action Required: Apply immediately"
echo ""

echo "=========================================="
echo "For detailed information, see:"
echo "  - DEPENDENCY_UPDATE_NOTES.md (Full docs)"
echo "  - UPGRADE_SUMMARY.md (Quick reference)"
echo "=========================================="
